name: master - build and deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Install Node.js 安装 nodejs 服务
              uses: actions/setup-node@v1
              with:
                  node-version: '10.x'

            - name: Install npm dependencies 安装模块
              run: yarn

            - name: Run build task 文档项目打包
              run: yarn docs:build

            - name: Deploy to Server 文档项目 部署到服务器
              uses: easingthemes/ssh-deploy@v2.0.7
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: 'docs/.vuepress/dist/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.REMOTE_TARGET_DOCS }}

            - name: Deploy to Server h5网页预览项目 部署到服务器
              uses: easingthemes/ssh-deploy@v2.0.7
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: 'unpackage/dist/build/h5/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.REMOTE_TARGET_PREVIEW }}
